server:
  port: 8000
spring:
  application:
    name: project-user-consumer
  zipkin:
     base-url: http://localhost:8780
     sender:
        type: web
  sleuth:
     sampler:
        percentage: 1.0 
        probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7778/eureka/
feign:
  hystrix:
    enabled: true
project-user-provider:
   ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule