server:
  port: 8000
spring:
  application:
    name: project-user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7778/eureka/
feign:
  hystrix:
    enabled: true
project-user-provider:
   ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule