server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7778/eureka/
spring:
  application:
    name: project-user-provider
  zipkin:
     base-url: http://localhost:8780
     sender:
        type: web
  sleuth:
     sampler:
        percentage: 1.0
        probability: 1
management:
   endpoints:
      web:
         exposure:
            include: beans,info,health
            