server:
  port: 7779
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7778/eureka/
spring:
  application:
    name: project-user-provider
management:
   endpoints:
      web:
         exposure:
            include: beans,info,health
            